/**
 * Comprehensive list of alcohol product types
 * Used to validate that product type matches are legitimate alcohol categories
 * rather than random words on the label
 */
export const ALCOHOL_TYPES = new Set([
  // ===== VODKA =====
  'vodka',
  'flavored vodka',
  'potato vodka',
  'grain vodka',
  'corn vodka',
  'wheat vodka',
  'rye vodka',

  // ===== WHISKEY/WHISKY =====
  // General
  'whiskey',
  'whisky',

  // American Whiskey
  'bourbon',
  'bourbon whiskey',
  'straight bourbon',
  'tennessee whiskey',
  'rye',
  'rye whiskey',
  'straight rye',
  'corn whiskey',
  'wheat whiskey',
  'american whiskey',
  'bottled in bond',
  'moonshine',

  // Scotch Whisky
  'scotch',
  'scotch whisky',
  'single malt',
  'single malt scotch',
  'blended scotch',
  'blended malt',
  'single grain',
  'blended whisky',
  'islay',
  'speyside',
  'highland',
  'lowland',
  'campbeltown',

  // Irish Whiskey
  'irish whiskey',
  'single pot still',
  'irish whisky',

  // Other Whiskey
  'canadian whisky',
  'japanese whisky',
  'japanese whiskey',
  'indian whisky',
  'welsh whisky',
  'australian whisky',
  'malt whisky',
  'malt whiskey',

  // ===== RUM =====
  'rum',
  'rhum',
  'ron',
  'white rum',
  'light rum',
  'silver rum',
  'clear rum',
  'dark rum',
  'black rum',
  'gold rum',
  'amber rum',
  'spiced rum',
  'aged rum',
  'añejo rum',
  'anejo rum',
  'overproof rum',
  'navy rum',
  'agricole',
  'rhum agricole',
  'demerara rum',
  'jamaican rum',
  'cuban rum',
  'puerto rican rum',
  'barbados rum',
  'martinique rum',
  'cachaca',
  'cachaça',

  // ===== GIN =====
  'gin',
  'london dry gin',
  'london dry',
  'plymouth gin',
  'old tom gin',
  'genever',
  'jenever',
  'navy strength gin',
  'navy strength',
  'contemporary gin',
  'new western gin',
  'sloe gin',
  'flavored gin',
  'barrel-aged gin',
  'compound gin',
  'distilled gin',

  // ===== TEQUILA & MEZCAL =====
  'tequila',
  'mezcal',
  'mescal',
  'blanco',
  'silver',
  'plata',
  'white tequila',
  'silver tequila',
  'joven',
  'gold',
  'gold tequila',
  'oro',
  'reposado',
  'añejo',
  'anejo',
  'extra añejo',
  'extra anejo',
  'cristalino',

  // ===== BRANDY & COGNAC =====
  'brandy',
  'cognac',
  'armagnac',
  'calvados',
  'applejack',
  'pisco',
  'grappa',
  'marc',
  'eau de vie',
  'eau-de-vie',
  'pomace brandy',
  'fruit brandy',
  'cherry brandy',
  'apple brandy',
  'pear brandy',
  'kirschwasser',
  'kirsch',
  'slivovitz',
  'palinka',
  'pálinka',
  'metaxa',

  // ===== LIQUEURS & CORDIALS =====
  'liqueur',
  'cordial',
  'cream liqueur',
  'crème liqueur',
  'creme liqueur',
  'amaro',
  'aperitif',
  'aperitivo',
  'digestif',
  'digestivo',
  'triple sec',
  'curaçao',
  'curacao',
  'blue curacao',
  'schnapps',
  'limoncello',
  'amaretto',
  'frangelico',
  'sambuca',
  'anisette',
  'ouzo',
  'pastis',
  'arak',
  'arrack',
  'raki',
  'kahlua',
  'coffee liqueur',
  'baileys',
  'irish cream',
  'cointreau',
  'grand marnier',
  'campari',
  'aperol',
  'chartreuse',
  'benedictine',
  'drambuie',
  'jägermeister',
  'jagermeister',
  'fernet',
  'fernet-branca',
  'cynar',
  'galliano',
  'midori',
  'chambord',
  'maraschino',
  'st-germain',
  'st germain',

  // ===== WINE - RED VARIETIES =====
  'wine',
  'red wine',
  'cabernet sauvignon',
  'cabernet',
  'cab sauv',
  'merlot',
  'pinot noir',
  'pinot',
  'syrah',
  'shiraz',
  'malbec',
  'zinfandel',
  'zin',
  'sangiovese',
  'tempranillo',
  'nebbiolo',
  'grenache',
  'garnacha',
  'petite sirah',
  'cabernet franc',
  'barbera',
  'gamay',
  'carmenere',
  'mourvedre',
  'monastrell',
  'nero d\'avola',
  'primitivo',
  'pinotage',
  'carignan',
  'petit verdot',
  'tannat',
  'aglianico',
  'montepulciano',
  'corvina',
  'dolcetto',

  // ===== WINE - WHITE VARIETIES =====
  'white wine',
  'chardonnay',
  'chard',
  'sauvignon blanc',
  'sauv blanc',
  'riesling',
  'pinot grigio',
  'pinot gris',
  'gewurztraminer',
  'gewürztraminer',
  'gewurz',
  'viognier',
  'chenin blanc',
  'semillon',
  'sémillon',
  'moscato',
  'muscat',
  'muscadet',
  'albarino',
  'albariño',
  'gruner veltliner',
  'grüner veltliner',
  'torrontes',
  'torrontés',
  'vermentino',
  'verdejo',
  'fiano',
  'greco',
  'assyrtiko',
  'soave',
  'trebbiano',
  'ugni blanc',
  'pinot blanc',
  'marsanne',
  'roussanne',

  // ===== WINE - SPARKLING =====
  'sparkling wine',
  'champagne',
  'prosecco',
  'cava',
  'cremant',
  'crémant',
  'sekt',
  'franciacorta',
  'lambrusco',
  'asti',
  'asti spumante',
  'spumante',
  'moscato d\'asti',
  'brut',
  'extra brut',
  'brut nature',
  'sec',
  'demi-sec',
  'doux',

  // ===== WINE - FORTIFIED & DESSERT =====
  'port',
  'porto',
  'ruby port',
  'tawny port',
  'vintage port',
  'lbv port',
  'sherry',
  'fino',
  'manzanilla',
  'amontillado',
  'oloroso',
  'palo cortado',
  'pedro ximenez',
  'px',
  'vermouth',
  'sweet vermouth',
  'dry vermouth',
  'bianco vermouth',
  'madeira',
  'marsala',
  'fortified wine',
  'dessert wine',
  'sweet wine',
  'ice wine',
  'eiswein',
  'late harvest',
  'sauternes',
  'tokaji',
  'tokay',
  'vin santo',
  'vinsanto',
  'vin de paille',
  'passito',
  'recioto',

  // ===== WINE - ROSÉ & OTHER =====
  'rosé',
  'rose',
  'rosado',
  'rosato',
  'blush wine',
  'white zinfandel',
  'orange wine',
  'amber wine',
  'natural wine',
  'biodynamic wine',
  'organic wine',
  'table wine',
  'vino da tavola',
  'vin de table',
  'vino de mesa',

  // ===== BEER - ALES =====
  'beer',
  'ale',
  'pale ale',
  'ipa',
  'india pale ale',
  'double ipa',
  'triple ipa',
  'imperial ipa',
  'session ipa',
  'new england ipa',
  'neipa',
  'hazy ipa',
  'west coast ipa',
  'american ipa',
  'english ipa',
  'belgian ipa',
  'amber ale',
  'red ale',
  'irish red ale',
  'brown ale',
  'english brown ale',
  'american brown ale',
  'blonde ale',
  'golden ale',
  'cream ale',
  'american ale',
  'british ale',
  'scotch ale',
  'wee heavy',
  'old ale',
  'strong ale',
  'bitter',
  'extra special bitter',
  'esb',
  'mild ale',
  'mild',
  'barleywine',
  'barley wine',
  'english barleywine',
  'american barleywine',

  // ===== BEER - STOUTS & PORTERS =====
  'stout',
  'porter',
  'dry stout',
  'irish stout',
  'irish dry stout',
  'oatmeal stout',
  'milk stout',
  'sweet stout',
  'cream stout',
  'imperial stout',
  'russian imperial stout',
  'ris',
  'foreign extra stout',
  'export stout',
  'chocolate stout',
  'coffee stout',
  'oyster stout',
  'baltic porter',
  'robust porter',
  'brown porter',
  'english porter',

  // ===== BEER - LAGERS =====
  'lager',
  'pilsner',
  'pilsener',
  'pils',
  'bohemian pilsner',
  'german pilsner',
  'czech pilsner',
  'american pilsner',
  'italian pilsner',
  'helles',
  'munich helles',
  'dunkel',
  'munich dunkel',
  'schwarzbier',
  'black lager',
  'märzen',
  'marzen',
  'oktoberfest',
  'festbier',
  'vienna lager',
  'amber lager',
  'dark lager',
  'american lager',
  'american light lager',
  'light lager',
  'pale lager',
  'dortmunder',
  'dortmunder export',
  'export lager',
  'bock',
  'traditional bock',
  'maibock',
  'helles bock',
  'doppelbock',
  'eisbock',
  'kellerbier',
  'zwickelbier',
  'rauchbier',
  'smoked lager',

  // ===== BEER - WHEAT & BELGIAN =====
  'wheat beer',
  'weissbier',
  'weißbier',
  'hefeweizen',
  'hefe',
  'american wheat',
  'american hefeweizen',
  'dunkelweizen',
  'weizenbock',
  'witbier',
  'white ale',
  'belgian white',
  'belgian wheat',
  'berliner weisse',
  'gose',
  'belgian ale',
  'belgian pale ale',
  'belgian blonde ale',
  'belgian golden ale',
  'belgian strong ale',
  'belgian dark strong ale',
  'dubbel',
  'tripel',
  'quadrupel',
  'quad',
  'belgian ipa',

  // ===== BEER - SOURS & WILD =====
  'sour',
  'sour ale',
  'wild ale',
  'lambic',
  'gueuze',
  'geuze',
  'kriek',
  'fruit lambic',
  'flanders red',
  'flanders red ale',
  'oud bruin',
  'flemish brown',
  'american sour',
  'fruit beer',
  'fruited sour',

  // ===== BEER - SPECIALTY & OTHER =====
  'malt liquor',
  'ice beer',
  'light beer',
  'session beer',
  'low alcohol beer',
  'non-alcoholic beer',
  'near beer',
  'radler',
  'shandy',
  'steam beer',
  'california common',
  'kölsch',
  'kolsch',
  'altbier',
  'alt',
  'saison',
  'farmhouse ale',
  'biere de garde',
  'sahti',
  'kvass',
  'chicha',

  // ===== CIDER & PERRY =====
  'cider',
  'hard cider',
  'apple cider',
  'dry cider',
  'sweet cider',
  'still cider',
  'sparkling cider',
  'farmhouse cider',
  'traditional cider',
  'modern cider',
  'perry',
  'pear cider',
  'poiré',

  // ===== SAKE & ASIAN SPIRITS =====
  'sake',
  'japanese sake',
  'junmai',
  'honjozo',
  'ginjo',
  'daiginjo',
  'junmai ginjo',
  'junmai daiginjo',
  'nigori',
  'nama',
  'genshu',
  'koshu',
  'soju',
  'shochu',
  'awamori',
  'baijiu',
  'huangjiu',
  'makgeolli',

  // ===== OTHER SPIRITS & BEVERAGES =====
  'absinthe',
  'absinth',
  'aquavit',
  'akvavit',
  'brennivín',
  'bitters',
  'angostura',
  'peychaud\'s',
  'mead',
  'honey wine',
  'tej',
  'pulque',
  'sotol',
  'raicilla',
  'singani',
  'tuica',
  'țuică',
  'mastika',
  'mastiha',
  'zivania',
  'boukha',
]);


/**
 * Check if text matches a known alcohol type
 */
export function isValidAlcoholType(text: string): boolean {
  const normalized = text.toLowerCase().trim();

  // Direct match
  if (ALCOHOL_TYPES.has(normalized)) {
    return true;
  }

  // Check if normalized text contains any valid type
  for (const type of ALCOHOL_TYPES) {
    if (normalized.includes(type)) {
      return true;
    }
  }

  return false;
}